DOSIEREINHEIT = {
    "#": "Messlöffel",
    "0": "Messbecher",
    "1": "Stück",
    "2": "Pkg.",
    "3": "Flasche",
    "4": "Beutel",
    "5": "Hub",
    "6": "Tropfen",
    "7": "Teelöffel",
    "8": "Esslöffel",
    "9": "E",
    "a": "Tasse",
    "b": "Applikatorfüllung",
    "c": "Augenbadewanne",
    "d": "Dosierbriefchen",
    "e": "Dosierpipette",
    "f": "Dosierspritze",
    "g": "Einzeldosis",
    "h": "Glas",
    "i": "Likörglas",
    "j": "Messkappe",
    "k": "Messschale",
    "l": "Mio E",
    "m": "Mio IE",
    "n": "Pipettenteilstrich",
    "o": "Sprühstoß",
    "p": "IE",
    "q": "cm",
    "r": "l",
    "s": "ml",
    "t": "g",
    "u": "kg",
    "v": "mg",
}